application: czfxhweb
version: 2
runtime: python
api_version: 1

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- xmpp_error

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /background
  script: queue.py

- url: .*
  script: main.py





